[55] Make assassins searchable
jsyiek/AU2 pull request #56
Opened 2024-11-08 22:34 UTC by jsyiek

**Problem**: A big time blocker for the umpires is finding assassins in the drop down. 

**Solution**: To make this easier, I've added a meta component for searching. It's the first component that isn't HTML compatible - I think for an HTML port, we'd discard the meta-component altogether.

**Testing**: I've tested it manually, searching for and adding assassins to an event

2024-11-09 15:03 UTC, thenewtonium requested changes

2024-11-09 21:26 UTC, jsyiek commented on AU2/frontends/inquirer_cli.py
> +            options = [o for o in options if any(f.lower() in o.lower() for f in filters)]
not sure I agree on enforcing `default` universally, but I've added a bit of reflection with `hasattr` to offer some run-time reflection for this

2024-11-10 17:52 UTC, thenewtonium commented on AU2/frontends/inquirer_cli.py
> +            options = [o for o in options if any(f.lower() in o.lower() for f in filters)]
Ah good point

In which case maybe the inclusion of default values in the options should happen in the `setter` function instead then, if the implementation of this behaviour of `Searchable` also depends on the idiosyncracies of its "sub-component"?

2024-11-10 17:54 UTC, thenewtonium approved these changes
lgtm

2024-11-10 18:27 UTC, jsyiek commented on AU2/frontends/inquirer_cli.py
> +            options = [o for o in options if any(f.lower() in o.lower() for f in filters)]
Yeah you're probably right. So that the umpires can have this, I'll merge this now and pull up a PR to change this later.

2024-11-10 18:28 UTC, jsyiek commented on AU2/frontends/inquirer_cli.py
> +            options = [o for o in options if any(f.lower() in o.lower() for f in filters)]
Ah, shoot, I've got merge conflicts...

2024-11-10 18:47 UTC, thenewtonium commented
I think that resolves the conflict correctly?

2024-11-10 18:49 UTC, merged