[64] Allow pseudonym replacement even if assassin is not in event
jsyiek/AU2 pull request #70
Opened 2024-11-14 21:51 UTC by jsyiek

Implements #64 

**Problem**: By default, when [PX]/etc. is in a report/headline and is not an assassin explicitly added to an event, the pseudonym is not rendered.

**Solution**: Allow it to be rendered by performing some regex search to figure out which assassins are in the report.

**Testing**: Manual

2024-11-15 00:07 UTC, thenewtonium requested changes

2024-11-15 00:12 UTC, thenewtonium commented
Testing this it has occured to me that hiding deleted pseudonyms makes it hard to figure out what the appropriate index for a given pseudonym is when using the [PX_i] format.

Perhaps blank pseudonyms shouldn't be hidden in Assassin -> Update (but still be hidden in Event -> Create and Event -> Update and when rendering [DX])...

2024-11-30 10:37 UTC, jsyiek commented on AU2/plugins/custom_plugins/PageGeneratorPlugin.py
> +                    candidate_pseudonyms.append((assassin_model, pseudonym, color))
Ah, good spot. The problem looks like it comes from here:

```
pseudonym_index = int(match[0] or 0)
```

2024-11-30 18:03 UTC, thenewtonium requested changes

2024-11-30 18:03 UTC, thenewtonium commented on AU2/plugins/custom_plugins/PageGeneratorPlugin.py
> +                    candidate_pseudonyms.append((assassin_model, pseudonym, color))
This still needs to be moved after the iteration over `e.assassins.items()`

2024-11-30 18:04 UTC, thenewtonium commented on AU2/plugins/custom_plugins/PageGeneratorPlugin.py
> +                    candidate_pseudonyms.append((assassin_model, pseudonym, color))
(not line +235 ofc)

2024-12-01 19:42 UTC, thenewtonium approved these changes
Lgtm!

2024-12-01 19:44 UTC, merged